#!/usr/bin/env bash
# sets up load balancers
sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 3909-web-01 100.25.31.37 check
\tserver 3909-web-02 18.215.160.9 check" | sudo tee -a $file
sudo service haproxy restart
