#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy=1.5

sed -i "s/ENABLE=0/ENABLE=1/" /etc/default/haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode: http\n\tdefault_backend nodes\n\n\nbackend nodes\n\tbalance roundrobin\n\tserver 3909-web-01 100.25.31.37 check\n\tserver 3909-web-02 18.215.160.9 check\n" >> /etc/haproxy/haproxy.cfg
