#!/usr/bin/env bash
# Gives you information about school file
FILE="school"
if [ -e $FILE ]
then
	echo "$FILE file exists"

	if [ -s $FILE ]
	then
		echo "$FILE file if not empty"
	else
		echo "$FILE file is empty"
	fi

	if [ -f $FILE ]
	then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file dose not exist"
fi
